services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exambyte
      POSTGRES_USER: exambyte
      POSTGRES_PASSWORD: iamgroot
    # TODO: For now for early dev commented out
    # volumes:
    #   - ./db_data/:/var/lib/postgresql/data

# volumes:
#   db_data:
